
- Memoria: Retener y recuperar información, desde hechos concretos hasta experiencias pasadas conocimiento 
- Inteligencia práctica: Uso de habilidades para manejar tareas diarias y tomar decisiones en el mundo real 
- Razonamiento lógico y crítico: Pensar de manera estructurada y evaluar argumentos, detectar inconsistencias y llegar a conclusiones informadas  
- Comunicación: Expresar ideas de manera efectiva y comprender mensajes orales o escritos en diversos contextos. analisis (información)
- Aprendizaje y adaptación: Habilidad para adquirir y asimilar nueva información, y ajustarse a cambios o entornos desconocidos  
- Pensamiento abstracto: Manejar conceptos e ideas más allá de lo tangible, como la resolución de ecuaciones matemáticas o la filosofía comprensión (datos)
- Resolución de problemas: analizar situaciones complejas, identificar problemas y desarrollar soluciones creativas o prácticas  sintesis (conocimiento)
- Creatividad: Generar ideas innovadoras y originales, combinando conceptos de maneras únicas
- Empatía y comprensión emocional: Reconocer, interpretar y responder a las emociones y necesidades de los demás 
- Inteligencia social: Navegar interacciones sociales, comprender dinámicas de grupo y desarrollar relaciones saludables evaluación (sabiduría)
