@startuml

state Magnificus {

    state Fundamentos {
        [*] --> Complejidad
        Complejidad --> Lenguajes
        Lenguajes --> Modelado
        Modelado --> Software
        Software --> [*]

    }
    state Calidad {
        state Programación {
            [*] --> Lenguajes
            Lenguajes --> Java
            Java --> JavaScript
            JavaScript --> 
        }
        state Diseño {
            [*] --> Principios
            Principios --> Patrones
            Patrones --> ArquitecturaSoftware
            ArquitecturaSoftware --> ArquitecturaSistema
            ArquitecturaSistema --> [*]
        }
        [*] --> Programación
        Programación --> Diseño
        Diseño --> Pruebas
        Pruebas --> [*]
    }
    state Proceso {
        [*] --> RUP
        RUP --> Safe
        Safe --> XP
        XP --> Scrum
        Scrum --> [*]
    }

    [*] --> Fundamentos
    Fundamentos --> Calidad
    Calidad --> Proceso
    Proceso --> [*]
}
@enduml

F-Ingeniería del Software
F-Complejidad

F-Lenguajes
F-Lógica

F-Modelado
F-Matemática

F-Aplicaciones
L-Datos

F-Proyectos
L-Consulta

I-Programacion
L-Publicación

I-Programación Imperativa
D-Principios de Legibilidad

I-Programación Basada en Objetos
D-Principios de Modularidad

I-Programación Orientada a Objetos
D-Principios de Extensibilidad

I-Programación Modular
D-Arquitectura del Software

I-Programación con Excepciones
D-Patrones de Diseño (Continuación)

I-Programación orientada a Aspectos
T-Pruebas Unitarias

I-Programación Concurrente
D-Frameworks

I-Programación Funcional
T-Pruebas Funcionales

T-Pruebas No Funcionales
P-Test First Development

P-RUP. Analisis
P-RUP. Requisitos

P-RUP. Diseño-Pruebas
P-RUP. Gestión

D-Refactoring
P-Test Drive Development

P-Scrum
P-ExtremePrograming

