@startuml

class Legibilidad #Red
class Minimización #Red
class Unificación #Red
class Uniformización #Red
class Modularidad #Green
class Abstracción #Green
class Autoprotección #Green
class Ocultación #Green
class Cohesión #Green
class Desacoplamiento #Green
class Granularización #Green
class Jerarquización #Green
class Solución #Green
class Problema #Green
class Extensibilidad #Blue
class Sustitución #Blue
class Especialización #Blue
class Generalización #Blue

Legibilidad -down-> Minimización 
Legibilidad -down-> Modularidad
Minimización -down-> Unificación
Minimización -down-> Sustitución
Sustitución -down-> Modularidad
Unificación -down-> Uniformización
Unificación -down-> Modularidad

Legibilidad -down-> Extensibilidad
Unificación -down-> Especialización
Uniformización -down-> Generalización

Modularidad -down-> Abstracción
Abstracción -down-> Autoprotección
Abstracción -down-> Cohesión
Autoprotección -down-> Ocultación

Modularidad -down-> Cohesión
Cohesión -down-> Desacoplamiento
Desacoplamiento -down-> Granularización

Modularidad -down-> Jerarquización
Jerarquización -down-> Solución
Jerarquización -down-> Cohesión
Solución -down-> Problema

Extensibilidad -down-> Sustitución 
Sustitución -down-> Especialización
Especialización -down-> Generalización


@enduml


Movilidad

Seguridad
Clima
Hora
Salud

Cuadro
Luces
Pedales
Volante

Contexto
- Ruta
Curvas
Cuestas
Baches

- Actores
Tráfico
Peatón
Animales

- Norma
Señal
Policia
Accidente



